
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  ru: {
    translation: {
      header: {
        address: 'Россия, Москва, 38КМ МКАД, 6бс1',
        hours: 'Время работы: с 08:00 до 21:00',
        whatsapp: 'Whatsapp',
        years: '10 лет',
        highlight: 'превосходим ваши ожидания',
        home: 'Подбор авто',
        company: 'О компании',
        services: 'Техцентр',
        reviews: 'Отзывы',
        contacts: 'Контакты',
        catalog: 'Каталог авто',
        catalogLoading: 'Загрузка марок...',
        catalogLoadError: 'Не удалось загрузить марки автомобилей.',
        used: 'Авто с пробегом',
        credit: 'Кредит и рассрочка',
        offers: 'Спецпредложения',
        specialOffer: 'Спецпредложение',
        taxi: 'Такси в кредит',
        compare: 'Сравнение',
        favorites: 'Избранное',
        search: 'Поиск авто...',
        callback: 'Обратный звонок',
        language: 'Язык',
        ru: 'Русский',
        en: 'English',
        phoneLabel: 'Контакты',
        catalogItem1: 'Внедорожники и кроссоверы',
        catalogItem2: 'Седаны',
        catalogItem3: 'Электромобили и гибриды',
        usedItem1: 'Проверенные с гарантией',
        usedItem2: 'Trade-in (Обмен)',
        creditItem1: 'Автокредит от 4.9%',
        creditItem2: 'Госпрограммы',
        offerItem1: 'Скидки месяца',
        offerItem2: 'Подарки при покупке',
      },
      home: {
        slide1: {
          label: 'Осталось всего 10 авто',
          title: 'Грандиозная распродажа тестового парка!',
          description: 'Узнай свою цену!',
        },
        slide2: {
          label: 'Автомобили в наличии',
          title: 'Подберите автомобиль для себя',
          description: 'Большой выбор автомобилей в каталоге',
        },
        slide3: {
          label: 'Выбор за вами',
          title: 'Ваш следующий автомобиль уже здесь',
          description: 'Выберите модель, которая подходит именно вам',
        },
        slide4: {
          label: 'Подбор автомобиля',
          title: 'Найдите автомобиль своей мечты',
          description: 'Посмотрите автомобили в каталоге',
        },
        slide5: {
          label: 'Каталог автомобилей',
          title: 'Выбирайте и сравнивайте автомобили',
          description: 'Подходящая модель начинается с выбора',
        },
        slide6: {
          label: 'Автомобили для вас',
          title: 'Пора выбрать свой автомобиль',
          description: 'Откройте каталог и найдите свою модель',
        },
      },
      homeAbout: {
        showroom: 'Автосалон',
        tradeIn: 'Трейд-ин',
        purchase: 'Покупка',
        title: 'Об автосалоне ABC',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pulvinar auctor tellus, id volutpat dui dictum vitae. Sed ac mauris nisi. Maecenas quis sollicitudin dolor, eget molestie dolor. Vivamus sed magna euismod, iaculis eros vitae, vehicula justo. Ut id consequat risus, vitae accumsan ligula. Proin egestas odio sit amet laoreet vulputate. Suspendisse vitae vestibulum quam. Vivamus lectus justo, bibendum at laoreet vel, rhoncus nec sem. Phasellus at mollis magna, in bibendum massa. Praesent malesuada erat nibh ut vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla iaculis a orci sit amet iaculis. Nulla in magna posuere nunc pharetra faucibus. Phasellus id enim libero.',
        hours: 'Ежедневно с 08:00 до 21:00',
        directions: 'Как до нас добраться',
        mapTitle: 'Карта расположения автосалона',
      },
      specialOffers: {
        title: 'Спецпредложения',
        previous: 'Предыдущие предложения',
        next: 'Следующие предложения',
        firstCar: 'Первый автомобиль',
        firstCarDescription: 'Выгодная программа для покупки вашего первого автомобиля.',
        familyCar: 'Семейный автомобиль',
        familyCarDescription: 'Программа покупки нового автомобиля для всей семьи.',
        expressCredit: 'Экспресс-кредит',
        expressCreditDescription: 'Получите решение по автокредиту быстро и удобно.',
        medical: 'Для работников медицины',
        medicalDescription: 'Специальные условия покупки автомобиля.',
        tradeIn: 'Выгодный Trade-in',
        tradeInDescription: 'Обменяйте старый автомобиль и получите скидку.',
        installment: 'Покупка в рассрочку',
        installmentDescription: 'Выберите удобный график платежей.',
        button: 'Узнать больше',
      },
      creditPage: {
        home: 'Главная',
        title: 'Кредит и рассрочка',
        rate: '1,9% по льготной ставке',
        button: 'Узнать больше',
        infoLabel: 'Специальная программа автокредитования',
        infoDescription: 'Выберите автомобиль и получите выгодные условия покупки в кредит.',
        rateLabel: 'Ставка от',
        perYear: 'годовых',
        benefitOne: 'Быстрое решение по заявке',
        benefitTwo: 'Первоначальный взнос от 0%',
        benefitThree: 'Выгодные условия кредитования',
        formTitle: 'Получите персональное предложение',
        name: 'Ваше имя',
        namePlaceholder: 'Введите имя',
        phone: 'Ваш телефон',
        submit: 'Оставить заявку',
        consent: 'Нажимая кнопку, вы соглашаетесь на обработку персональных данных.',
        thanks: 'Спасибо! Ваша заявка принята.',
        offers: {
          firstCar: 'Первый автомобиль',
          familyCar: 'Семейный автомобиль',
          expressCredit: 'Экспресс-кредит',
          medical: 'Работникам медицины',
          installment: 'Рассрочка',
          tradeIn: 'Госпрограмма Trade-in',
        },
      },
      favoritesPage: {
        home: 'Главная',
        title: 'Избранное',
        newCars: 'Новые авто {{count}}',
        usedCars: 'С пробегом 0',
        taxi: 'Такси 0',
        newCarsTitle: 'Новые авто',
        selectedCount: 'Выбрано {{count}} авто',
        specialOffer: 'Предложение дилера',
        remove: 'Убрать из избранного',
        available: 'В наличии',
        creditProgram: 'Выгодная программа кредита',
        benefits: 'Скидка и подарки при покупке',
        warranty: 'Гарантия на автомобиль',
        priceFrom: 'от {{price}}',
        details: 'Подробнее',
        buy: 'Купить',
        offer: 'Предложение',
        empty: 'В избранном пока нет автомобилей',
        catalog: 'Перейти в каталог',
      },
      companyVideo: {
        title: 'О компании',
        description: 'Мы помогаем подобрать автомобиль и сопровождаем клиентов на каждом этапе покупки. Познакомьтесь с нашей командой и узнайте больше об автосалоне.',
      },
      blog: {
        title: 'Блог',
        allArticles: 'Все статьи',
        date: '12 октября 2024',
        articleTitle: 'Тест Skoda Kodiaq Sportline: обзор и впечатления',
        imageAlt: 'Семья выбирает автомобиль',
      },
      infoCar: {
        loading: 'Загрузка автомобиля…',
        notFound: 'Автомобиль не найден.',
        loadError: 'Не удалось загрузить данные автомобиля.',
        brandCarsTitle: 'Автомобили {{brand}} в наличии',
        specification: 'Комплектация и характеристики',
        priceOnRequest: 'Цена по запросу',
        trim: 'Комплектация',
        availableCount: '{{count}} авто',
        fullDescription: 'Полное описание',
        hideDescription: 'Свернуть описание',
        reserve: 'Забронировать',
        advertisement: {
          offer: 'Акция до 20.02.2021',
          title: 'Станьте владельцем {{model}} уже сегодня',
          car: 'своего автомобиля',
          formTitle: 'ВАШЕ ПЕРСОНАЛЬНОЕ ПРЕДЛОЖЕНИЕ',
          consent: 'Нажимая кнопку «Получить предложение», вы соглашаетесь с политикой обработки персональных данных.',
          carAlt: 'Белый автомобиль Toyota',
        },
        similarOffers: {
          title: 'Похожие предложения',
          previous: 'Предыдущие предложения',
          next: 'Следующие предложения',
          discount: 'Предложение дня',
          insurance: 'Оборудование в подарок',
          casco: 'КАСКО в подарок',
          gift: 'Комплект резины в подарок',
          credit: 'Кредит от 115 000 ₽/мес.',
          reserve: 'Резерв онлайн',
          buy: 'Купить',
          carAlt: 'Автомобиль без фона',
          showMore: 'Показать еще',
          showLess: 'Свернуть',
        },
        safety: 'Безопасность',
        safetyItems: [
          'Запасное колесо неполноразмерное',
          'Передние тормоза: дисковые',
          'Задние тормоза: барабанные',
          'Задние колеса: 175/65R14',
          'Передние колеса: 175/65R14',
          'Передний стабилизатор',
          'Передняя подвеска: независимая, амортизационная стойка типа МакФерсон',
        ],
        exterior: 'Экстерьер',
        exteriorItems: [
          'Задняя подвеска: полузависимая, торсионная балка',
          'Иммобилайзер',
          'Вспомогательная система торможения (BAS)',
          'Антиблокировочная система торможения (ABS)',
          'Система помощи при старте на подъеме (HAC)',
          'Система электронного контроля устойчивости (ESP)',
          'Система контроля давления в шинах',
          'Подушка безопасности водительская',
        ],
        interior: 'Интерьер',
        interiorItems: [
          'Подушка безопасности пассажира с функцией деактивации',
          'Подушка безопасности переднего пассажира',
          'Дополнительный стоп-сигнал',
          'ЭРА-ГЛОНАСС',
          'Крепление ISOFIX',
        ],
        offers: {
          specialTitle: 'Специальное предложение',
          representative: 'от представительства',
          availabilityTitle: 'Скидка за наличие',
          dealer: 'от ABC Auto',
          tradeInTitle: 'Выгода за Trade-in',
          recyclingTitle: 'Выгода за утилизацию',
          creditTitle: 'Скидка при оформлении',
          creditSubtitle: 'Авто в кредит 1,9%',
          stateTitle: 'Госпрограмма',
          stateSubtitle: 'Семейный автомобиль, Первый автомобиль, работникам медицины и другие программы',
          stateValue: '10% от цены авто',
          details: 'Подробнее',
          maximumDiscount: 'Максимальная скидка',
          upTo: 'до {{amount}}',
          yourDiscount: 'Ваша скидка',
          confirmTerms: 'Зафиксировать условия',
          termsConfirmed: 'Условия зафиксированы',
          enable: 'Включить: {{offer}}',
          disable: 'Выключить: {{offer}}',
        },
      },
      carDetails: {
        previousImage: 'Предыдущее фото',
        nextImage: 'Следующее фото',
        showImage: 'Показать фото {{number}}',
        views: 'Автомобиль просмотрели {{count}} раз',
        description: 'Характеристики выбранного автомобиля',
        creditPrice: '{{price}} ₽/мес. по кредиту',
        reserve: 'Забронировать онлайн',
        buyOnCredit: 'Купить в кредит',
        tradeIn: 'Зачёт вашего автомобиля в Trade-in',
        credit: 'Рассрочка и кредит',
        fields: {
          year: 'Год',
          mileage: 'Пробег',
          transmission: 'Коробка передач',
          drive: 'Привод',
          bodyType: 'Кузов',
          engine: 'Двигатель',
          power: 'Мощность',
          color: 'Цвет',
        },
        units: {
          mileage: 'км',
          transmission: '',
          drive: '',
          engine: '',
          power: 'л.с.',
        },
      },
      comparePage: {
        home: 'Главная',
        title: 'Сравнение',
        cars: 'Автомобили',
        showDifferences: 'Показать различия',
        empty: 'Добавьте автомобили к сравнению в каталоге.',
        previous: 'Предыдущие автомобили',
        next: 'Следующие автомобили',
        toggleFavorite: 'Добавить или убрать из избранного',
        remove: 'Удалить из сравнения',
        fields: {
          price: 'Стоимость',
          discountPrice: 'Стоимость со скидкой',
          condition: 'Состояние',
          region: 'Регион',
          brand: 'Марка',
          model: 'Модель',
          modification: 'Модификация',
          engine: 'Тип двигателя',
          transmission: 'КПП',
          bodyType: 'Тип кузова',
          mileage: 'Пробег',
          drive: 'Тип привода',
          year: 'Год выпуска',
          power: 'Мощность',
        },
      },
      brand: {
        title: 'Быстрый подбор авто',
        price: 'Цена',
        bodyType: 'Тип кузова',
        transmission: 'Коробка',
        show: 'Показать 73',
        optionSedan: 'Седан',
        optionSuv: 'Внедорожник',
        optionHatchback: 'Хэтчбек',
        optionAuto: 'Автомат',
        optionManual: 'Механика',
        optionRobot: 'Робот',
        emptyBody: 'Тип кузова',
        emptyTransmission: 'Коробка',
        priceScale: ['0', '500т', '800т', '1,1м', '1,4м', '1,7м', '2м', '2,3м', '2,7м', '3м'],
      },
      reviews: {
        breadcrumbsHome: 'Главная',
        breadcrumbsCurrent: 'Отзывы',
        title: 'Отзывы',
        more: 'Подробнее',
        less: 'Свернуть',
        loadMore: 'Показать ещё',
        play: 'Смотреть видео',
        pause: 'Остановить видео',
      },
      boxing: {
        title: 'Отзывы',
        author: 'Сергей Васильев',
        shortText: '«Я нахожусь в салоне ALTERA, всем советую, хороший коллектив, добрые люди, приветствуют, это не обман, вам гарантия 100 % точно, чисто от меня, приезжайте! Мы приехали приобрести автомобиль в салон ALTERA...»',
        fullText: '«Я нахожусь в салоне ALTERA, всем советую. Здесь хороший коллектив, добрые и приветливые люди. Это не обман — вам точно гарантируют 100%. Приезжайте! Мы приехали приобрести автомобиль в салон ALTERA и остались довольны обслуживанием и покупкой.»',
        more: 'Подробнее',
        less: 'Свернуть',
        play: 'Смотреть видео',
        pause: 'Остановить видео',
      },
      punch: {
        title: 'ПЕРЕБЬЁМ ПРЕДЛОЖЕНИЯ ОТ КОНКУРЕНТОВ!',
        subtitle: 'Скидки от 10 до 20% на стоимость автомобиля',
        button: 'Получить предложение',
        consent: 'Нажимая кнопку «Отправить», вы даёте согласие на обработку своих персональных данных.',
      },
      archive: {
        title: 'Архивные модели',
        modelName: 'Toyota Prius',
        benefit: 'Выгода до 300 000 ₽',
        details: 'Подробнее',
        book: 'Забронировать',
      },
      gos: {
        title: 'Семейный автомобиль — программа господдержки',
        rate: 'Рейтинг 4.8',
        rateDescription: '450 отзывов',
        discount: 'Скидка 10% и низкий кредит 5.9%',
        description: 'Беспроцентная рассрочка 12 месяцев до 500 000 рублей',
        button: 'Оставить заявку',
        consent: 'Нажимая кнопку, вы даёте согласие на обработку своих персональных данных.',
        familyAlt: 'Семья с ребёнком',
      },
      trust: {
        title: 'Нам доверяют',
        siteName: 'Сайт отзывов',
        dealerName: 'Название автосалона',
        recommend: 'Рекомендуют 90%',
        maps: 'Maps',
        previous: 'Предыдущие оценки',
        next: 'Следующие оценки',
      },
      footer: {
        catalog: 'Каталог авто',
        used: 'Авто с пробегом',
        credit: 'Кредит и рассрочка',
        offers: 'Спецпредложения',
        taxi: 'Такси в кредит',
        more: 'Подробнее',
        sitemap: 'Карта сайта',
        catalogTitle: 'КАТАЛОГ',
        catalogTitle2: 'АВТО',
        creditTitle: 'Кредит и рассрочка',
        express: 'Экспресс-кредит',
        family: 'Семейный автомобиль',
        firstCar: 'Первый автомобиль',
        medical: 'Работникам медицины',
        installment: 'Рассрочка',
        servicesTitle: 'Техцентр',
        warranty: 'Гарантия',
        service: 'Сервис',
        contactsTitle: 'Контакты',
        hours: 'Ежедневно с 08:00 до 21:00',
        address: 'Россия, Москва, 38КМ МКАД, 6бс1',
        route: 'Схема проезда',
        city: 'Москва',
        copyright: '© 2021 Автосалон "ABC AUTO". Официальный дилер',
        privacy: 'Политика конфиденциальности',
        agreement: 'Пользовательское соглашение',
        disclaimer: 'Обращаем Ваше внимание на то, что данный интернет-сайт носит исключительно информационный характер и ни при каких условиях не является публичной офертой, определяемой положениями Статьи 437 Гражданского кодекса Российской Федерации.',
        ratingAlt: 'Рейтинг организации в Яндекс',
      },
      services: {
        breadcrumbsHome: 'Главная',
        breadcrumbsCurrent: 'Техцентр',
        title: 'Техцентр',
        intro: 'Специалисты нашего автосервиса имеют огромный опыт в обслуживании автомобилей разных производителей, новых и с пробегом, поэтому в короткие сроки способны обнаружить и исправить любую поломку. Все работы проводятся в соответствии с рекомендациями производителей.',
        bodyRepair: 'Кузовной ремонт',
        bodyRepairText: 'Современное оборудование позволяет осуществлять кузовной ремонт любой сложности. Работаем только с качественными материалами от проверенных поставщиков.',
        repair: 'Слесарный ремонт',
        repairText: 'Выполняем как текущий, так и капитальный слесарный ремонт, в том числе обслуживание силовой установки.',
        tire: 'Шиномонтаж',
        tireText: 'Своевременная замена резины необходима для безаварийной езды. Ориентируемся на пробег, состояние резины и время года.',
        diagnostics: 'Диагностика',
        diagnosticsText: 'Качественная диагностика позволяет выявить не только имеющиеся проблемы, но и предупредить возможные, поэтому процедура проводится в плановом порядке.',
        oilChange: 'Замена масла',
        oilChangeText: 'Это необходимая процедура, значительно увеличивающая ресурс двигателя, а также позволяющая минимизировать негативные последствия использования некачественного топлива.',
        maintenance: 'Техническое обслуживание',
        maintenanceText: 'Это обеспечивают бесперебойную работу основных узлов и агрегатов ТС.',
        wheelAlignment: 'Сход-развал',
        wheelAlignmentText: 'Процедура обеспечивает устойчивость автомобиля на дороге. Проводится планово или в связи с нарушениями управляемости.',
        parts: 'Подбор запчастей',
        partsText: 'Надёжность автомобиля напрямую зависит от качества запчастей. Услуга позволяет подобрать качественную деталь, подходящую к конкретному автомобилю.',
        insurance: 'Продление страховых полисов',
        insuranceText: 'Мы подберём честную компанию, предлагающую страховку по адекватным ценам. Это позволит избежать попадания в мошеннические схемы.',
      },
      contacts: {
        breadcrumbsHome: 'Главная',
        breadcrumbsCurrent: 'Контакты',
        title: 'Контакты',
        phone: 'Телефон',
        address: 'Адрес',
        addressValue: 'Россия, Москва, 38КМ МКАД, 6Бс1',
        route: 'Как проехать',
        routeMkadIn: 'от МКАД (внутренняя сторона)',
        routeMkadOut: 'от МКАД (внешняя сторона)',
        routeCity: 'из области, из центра',
        company: 'О компании',
        companyText: 'Мы располагаем огромной торговой площадкой более 5000 квадратных метров, у нас в наличии не менее 200 автомобилей как отечественного, так и иностранного производства. В штате автосалона «Альтера» работают настоящие профессионалы, которые знают особенности каждого конкретного автомобиля.',
        slideLabel: 'Слайд',
        mapAlt: 'Карта города присутствия',
        city: 'Москва',
      },
      company: {
        breadcrumbsHome: 'Главная',
        breadcrumbsCurrent: 'О компании',
        title: 'О компании',
        intro: 'Официальный дилер Азимут Варшавка предлагает широкий выбор автомобилей различных цветов и комплектаций на самых выгодных условиях. На территории автосалона представлено свыше двухсот новых автомобилей и с пробегом. Среди ассортимента представленных автомобилей встречаются наиболее популярные представители европейского, азиатского и российского производства. Для каждого клиента в нашем автосалоне предоставляется полная персональная консультация по любому из представленных автомобилей. Подробнее о представленных в салоне моделях Вы можете узнать на сайте и у наших менеджеров.',
        benefitTitle: 'Выбирая автосалон Азимут Варшавка Вы получаете:',
        benefits: [
          'самые выгодные цены на автомобили в Москве;',
          'возможность выбора автомобилей более чем из двухсот моделей различных цветов и комплектаций;',
          'приобретение автомобилей с пробегом, прошедших предпродажную подготовку и юридическую экспертизу;',
          'быстрое и качественное оформление документов;',
          'высокий уровень сервиса и индивидуальный подход;',
          'выгодное приобретение автомобиля по программам Trade-in и утилизация;',
          'сотрудничество с самыми крупными банками Москвы, предлагающими наиболее выгодные условия кредитования;',
          'возможность участия в программах льготного кредитования «Семейный автомобиль», и «Первый автомобиль», а также льготное условия для медицинских работников и тех, кто сдает свой автомобиль по программе Trade-in в счёт оплаты первоначального взноса;',
          'акции и подарки от автосалона при покупке автомобиля.'
        ],
        shouldKnow: 'Все вопросы о наличии, цветах и комплектациях автомобилей, а также по работе автосалона Вы всегда можете узнать по телефону, указанному на сайте, а также при помощи формы обратной связи.',
        gratitude: 'Мы ценим каждого клиента и гарантируем высокий уровень сервиса!',
        slogan: 'Азимут Варшавка — с нами Вам покорятся все направления!',
        photoTitle: 'Фото автосалона',
        citiesTitle: 'Городов присутствия',
        workers: 'работников',
        experience: 'на рынке',
        partnerBanks: 'Банки-партнеры',
        cityGroups: {
          col1: [
            { id: 1, name: 'Москва' },
            { id: 2, name: 'Санкт-Петербург' },
            { id: 3, name: 'Нижний Новгород' },
            { id: 4, name: 'Краснодар' }
          ],
          col2: [
            { id: 5, name: 'Астрахань' },
            { id: 6, name: 'Вологда' },
            { id: 7, name: 'Тула' },
            { id: 8, name: 'Архангельск' }
          ]
        }
      },
      brandInfo: {
        notFound: 'Марка не найдена',
        backHome: 'Вернуться на главную',
        filteredTitle: 'Автомобили по выбранной цене',
        found: 'Найдено моделей',
        empty: 'В этом диапазоне автомобилей не найдено.',
        breadcrumbsHome: 'Главная',
        breadcrumbsCatalog: 'Каталог авто',
        saleTitle: 'Грандиозная распродажа',
        saleText: 'Получите специальную цену и подарок на выбор при покупке авто',
        discountLabel: 'Скидки до',
        guarantee: 'Гарантия',
        bestPrice: 'лучшей цены',
        credit: 'Выгодный',
        creditText: 'кредит',
        tradeInTitle: 'Зачёт вашего авто',
        tradeInText: 'в trade-in',
        giftTitle: 'Подарок на выбор',
        giftText: 'при покупке авто',
        favourite: 'Избранное и сравнение',
        favoriteCompare: 'Избранное и сравнение',
        inStock: 'В наличии',
        deal: 'Покупка в трейд-ин',
        creditOffer: 'Кредит',
        sale: 'Распродажа',
        insurance: 'Страхование',
        insuranceGift: 'в подарок',
        casco: 'КАСКО',
        tireKit: 'Комплект резины',
        benefitUpTo: 'Выгода до',
        from: 'от',
        colorNames: {
          white: 'Белый',
          pearlWhite: 'Белый перламутр',
          black: 'Черный',
          blackMetallic: 'Черный металлик',
          grey: 'Серый',
          greyMetallic: 'Серый металлик',
          silver: 'Серебристый',
          brown: 'Коричневый',
          red: 'Красный',
          brightRed: 'Ярко-красный',
          blue: 'Синий',
          green: 'Зеленый',
          orange: 'Оранжевый',
          yellow: 'Желтый'
        },
        chooseColor: 'Выбрать цвет',
        compare: 'Сравнить',
        details: 'Подробнее',
        buyWithDiscount: 'Купить со скидкой',
        calculateCredit: 'Рассчитать кредит',
        moreModel: 'Подробнее о модели',
        carAlt: 'Автомобиль',
        specialPriceTitle: 'Получите специальную цену',
        specialPriceOnly: 'Только до 10.10.21',
        yourName: 'Ваше имя',
        yourPhone: 'Ваш телефон',
        getOffer: 'Получить предложение',
        consent: 'Нажимая кнопку, вы даёте согласие на обработку своих персональных данных.',
        thanks: 'Спасибо! Ваша заявка принята.',
        modelRangeTitle: 'Модельный ряд и цены автомобилей',
        emptyRange: 'У этой марки нет моделей в выбранном диапазоне цен.',
      },
      error: {
        navCatalog: 'Каталог авто',
        navTradeIn: 'Trade-in',
        navCredit: 'Экспресс кредит',
        navContacts: 'Контакты',
        title: 'Страница не найдена!',
        message: 'Мы запустили новый сайт, сделав его удобным и информативным. Возможно, запрашиваемая вами страница была перенесена или удалена. Вы можете позвонить нам и получить квалифицированную помощь наших специалистов.',
        home: 'На главную',
      },
    }
  },
  en: {
    translation: {
      header: {
        address: 'Russia, Moscow, 38KM MKAD, 6bс1',
        hours: 'Working hours: from 08:00 to 21:00',
        whatsapp: 'Whatsapp',
        years: '10 years',
        highlight: 'we exceed your expectations',
        home: 'Vehicle selection',
        company: 'About us',
        services: 'Service center',
        reviews: 'Reviews',
        contacts: 'Contacts',
        catalog: 'Car catalog',
        catalogLoading: 'Loading car brands...',
        catalogLoadError: 'Unable to load car brands.',
        used: 'Used cars',
        credit: 'Credit and installment',
        offers: 'Special offers',
        specialOffer: 'Special offer',
        taxi: 'Taxi in credit',
        compare: 'Comparison',
        favorites: 'Favorites',
        search: 'Search car...',
        callback: 'Call back',
        language: 'Language',
        ru: 'Русский',
        en: 'English',
        phoneLabel: 'Contacts',
        catalogItem1: 'SUVs and crossovers',
        catalogItem2: 'Sedans',
        catalogItem3: 'Electric and hybrid cars',
        usedItem1: 'Verified with warranty',
        usedItem2: 'Trade-in (Exchange)',
        creditItem1: 'Auto loan from 4.9%',
        creditItem2: 'State programs',
        offerItem1: 'Monthly discounts',
        offerItem2: 'Gifts with purchase',
      },
      home: {
        slide1: {
          label: 'Only 10 cars left',
          title: 'Grand sale of the test fleet!',
          description: 'Find out your price!',
        },
        slide2: {
          label: 'Cars in stock',
          title: 'Choose a car for yourself',
          description: 'A wide range of cars in the catalog',
        },
        slide3: {
          label: 'The choice is yours',
          title: 'Your next car is already here',
          description: 'Choose the model that fits you best',
        },
        slide4: {
          label: 'Car selection',
          title: 'Find the car of your dreams',
          description: 'Look through the cars in the catalog',
        },
        slide5: {
          label: 'Car catalog',
          title: 'Choose and compare cars',
          description: 'The right model starts with a choice',
        },
        slide6: {
          label: 'Cars for you',
          title: 'It is time to choose your car',
          description: 'Open the catalog and find your model',
        },
      },
      homeAbout: {
        showroom: 'Showroom',
        tradeIn: 'Trade-in',
        purchase: 'Purchase',
        title: 'About ABC dealership',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pulvinar auctor tellus, id volutpat dui dictum vitae. Sed ac mauris nisi. Maecenas quis sollicitudin dolor, eget molestie dolor. Vivamus sed magna euismod, iaculis eros vitae, vehicula justo. Ut id consequat risus, vitae accumsan ligula. Proin egestas odio sit amet laoreet vulputate. Suspendisse vitae vestibulum quam. Vivamus lectus justo, bibendum at laoreet vel, rhoncus nec sem. Phasellus at mollis magna, in bibendum massa. Praesent malesuada erat nibh ut vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla iaculis a orci sit amet iaculis. Nulla in magna posuere nunc pharetra faucibus. Phasellus id enim libero.',
        hours: 'Daily from 08:00 to 21:00',
        directions: 'How to get there',
        mapTitle: 'Map showing the showroom location',
      },
      specialOffers: {
        title: 'Special offers',
        previous: 'Previous offers',
        next: 'Next offers',
        firstCar: 'First car',
        firstCarDescription: 'A great program for buying your first car.',
        familyCar: 'Family car',
        familyCarDescription: 'A new-car program for the whole family.',
        expressCredit: 'Express credit',
        expressCreditDescription: 'Get a car loan decision quickly and easily.',
        medical: 'For medical workers',
        medicalDescription: 'Special terms for buying a car.',
        tradeIn: 'Trade-in offer',
        tradeInDescription: 'Exchange your old car and get a discount.',
        installment: 'Installment plan',
        installmentDescription: 'Choose a payment schedule that works for you.',
        button: 'Learn more',
      },
      creditPage: {
        home: 'Home',
        title: 'Credit and installment',
        rate: '1.9% special rate',
        button: 'Learn more',
        infoLabel: 'Special car financing program',
        infoDescription: 'Choose a car and get favorable financing terms.',
        rateLabel: 'Rate from',
        perYear: 'per year',
        benefitOne: 'Fast application decision',
        benefitTwo: 'Down payment from 0%',
        benefitThree: 'Favorable financing terms',
        formTitle: 'Get a personal offer',
        name: 'Your name',
        namePlaceholder: 'Enter your name',
        phone: 'Your phone',
        submit: 'Request an offer',
        consent: 'By submitting, you agree to the processing of your personal data.',
        thanks: 'Thank you! Your request has been received.',
        offers: {
          firstCar: 'First car',
          familyCar: 'Family car',
          expressCredit: 'Express credit',
          medical: 'For medical workers',
          installment: 'Installment plan',
          tradeIn: 'Government Trade-in program',
        },
      },
      favoritesPage: {
        home: 'Home',
        title: 'Favorites',
        newCars: 'New cars {{count}}',
        usedCars: 'Used 0',
        taxi: 'Taxi 0',
        newCarsTitle: 'New cars',
        selectedCount: '{{count}} cars selected',
        specialOffer: 'Dealer offer',
        remove: 'Remove from favorites',
        available: 'Available',
        creditProgram: 'Favorable financing program',
        benefits: 'Discount and gifts with purchase',
        warranty: 'Vehicle warranty',
        priceFrom: 'from {{price}}',
        details: 'Details',
        buy: 'Buy',
        offer: 'Offer',
        empty: 'There are no cars in your favorites yet',
        catalog: 'Browse cars',
      },
      companyVideo: {
        title: 'About us',
        description: 'We help customers choose a car and support them through every step of the purchase. Meet our team and learn more about the dealership.',
      },
      blog: {
        title: 'Blog',
        allArticles: 'All articles',
        date: 'October 12, 2024',
        articleTitle: 'Skoda Kodiaq Sportline test: review and impressions',
        imageAlt: 'Family choosing a car',
      },
      infoCar: {
        loading: 'Loading car…',
        notFound: 'Car not found.',
        loadError: 'Unable to load car details.',
        brandCarsTitle: '{{brand}} cars in stock',
        specification: 'Trim and specifications',
        priceOnRequest: 'Price on request',
        trim: 'Trim',
        availableCount: '{{count}} cars',
        fullDescription: 'Full description',
        hideDescription: 'Hide description',
        reserve: 'Reserve',
        advertisement: {
          offer: 'Offer valid until 20.02.2021',
          title: 'Own {{model}} today',
          car: 'your new car',
          formTitle: 'YOUR PERSONAL OFFER',
          consent: 'By clicking “Get an offer”, you agree to the processing of your personal data.',
          carAlt: 'White Toyota car',
        },
        similarOffers: {
          title: 'Similar offers',
          previous: 'Previous offers',
          next: 'Next offers',
          discount: 'Offer of the day',
          insurance: 'Equipment as a gift',
          casco: 'CASCO insurance as a gift',
          gift: 'Tire set as a gift',
          credit: 'Credit from ₽115,000/month',
          reserve: 'Reserve online',
          buy: 'Buy',
          carAlt: 'Car with transparent background',
          showMore: 'Show more',
          showLess: 'Show less',
        },
        safety: 'Safety',
        safetyItems: [
          'Space-saver spare wheel',
          'Front disc brakes',
          'Rear drum brakes',
          'Rear wheels: 175/65R14',
          'Front wheels: 175/65R14',
          'Front stabilizer bar',
          'Front suspension: independent MacPherson strut',
        ],
        exterior: 'Exterior',
        exteriorItems: [
          'Rear suspension: semi-independent torsion beam',
          'Immobilizer',
          'Brake assist system (BAS)',
          'Anti-lock braking system (ABS)',
          'Hill-start assist control (HAC)',
          'Electronic stability program (ESP)',
          'Tire pressure monitoring system',
          'Driver airbag',
        ],
        interior: 'Interior',
        interiorItems: [
          'Passenger airbag with deactivation function',
          'Front passenger airbag',
          'Additional brake light',
          'ERA-GLONASS emergency response system',
          'ISOFIX child seat anchors',
        ],
        offers: {
          specialTitle: 'Special offer',
          representative: 'from the representative',
          availabilityTitle: 'In-stock discount',
          dealer: 'from ABC Auto',
          tradeInTitle: 'Trade-in benefit',
          recyclingTitle: 'Recycling discount',
          creditTitle: 'Financing discount',
          creditSubtitle: 'Car loan from 1.9%',
          stateTitle: 'State program',
          stateSubtitle: 'Family Car, First Car, medical workers and other programs',
          stateValue: '10% of car price',
          details: 'Details',
          maximumDiscount: 'Maximum discount',
          upTo: 'up to {{amount}}',
          yourDiscount: 'Your discount',
          confirmTerms: 'Confirm terms',
          termsConfirmed: 'Terms confirmed',
          enable: 'Enable {{offer}}',
          disable: 'Disable {{offer}}',
        },
      },
      carDetails: {
        previousImage: 'Previous photo',
        nextImage: 'Next photo',
        showImage: 'Show photo {{number}}',
        views: 'Viewed {{count}} times',
        description: 'Selected car specifications',
        creditPrice: '{{price}} ₽/month on credit',
        reserve: 'Reserve online',
        buyOnCredit: 'Buy on credit',
        tradeIn: 'Trade-in for your car',
        credit: 'Installment and credit',
        fields: {
          year: 'Year',
          mileage: 'Mileage',
          transmission: 'Transmission',
          drive: 'Drive',
          bodyType: 'Body',
          engine: 'Engine',
          power: 'Power',
          color: 'Color',
        },
        units: {
          mileage: 'km',
          transmission: '',
          drive: '',
          engine: '',
          power: 'hp',
        },
      },
      comparePage: {
        home: 'Home',
        title: 'Comparison',
        cars: 'Cars',
        showDifferences: 'Show differences',
        empty: 'Add cars to comparison from the catalog.',
        previous: 'Previous cars',
        next: 'Next cars',
        toggleFavorite: 'Add or remove from favorites',
        remove: 'Remove from comparison',
        fields: {
          price: 'Price',
          discountPrice: 'Discounted price',
          condition: 'Condition',
          region: 'Region',
          brand: 'Make',
          model: 'Model',
          modification: 'Modification',
          engine: 'Engine type',
          transmission: 'Transmission',
          bodyType: 'Body type',
          mileage: 'Mileage',
          drive: 'Drive type',
          year: 'Year',
          power: 'Power',
        },
      },
      brand: {
        title: 'Quick car selection',
        price: 'Price',
        bodyType: 'Body type',
        transmission: 'Transmission',
        show: 'Show 73',
        optionSedan: 'Sedan',
        optionSuv: 'SUV',
        optionHatchback: 'Hatchback',
        optionAuto: 'Automatic',
        optionManual: 'Manual',
        optionRobot: 'Robot',
        emptyBody: 'Body type',
        emptyTransmission: 'Transmission',
        priceScale: ['0', '500k', '800k', '1.1m', '1.4m', '1.7m', '2m', '2.3m', '2.7m', '3m'],
      },
      reviews: {
        breadcrumbsHome: 'Home',
        breadcrumbsCurrent: 'Reviews',
        title: 'Reviews',
        more: 'More',
        less: 'Collapse',
        loadMore: 'Show more',
        play: 'Watch video',
        pause: 'Pause video',
      },
      boxing: {
        title: 'Reviews',
        author: 'Sergey Vasilyev',
        shortText: '“I am at the ALTERA showroom and recommend it to everyone. The team is friendly and welcoming, and everything is honest, with a 100% guarantee. Come visit! We came to buy a car at the ALTERA showroom...”',
        fullText: '“I am at the ALTERA showroom and recommend it to everyone. The team is friendly and welcoming. Everything is honest, with a 100% guarantee. Come visit! We came to buy a car at the ALTERA showroom and were happy with the service and our purchase.”',
        more: 'Read more',
        less: 'Collapse',
        play: 'Play review video',
        pause: 'Pause review video',
      },
      punch: {
        title: 'WE WILL BEAT OUR COMPETITORS’ OFFERS!',
        subtitle: 'Get 10% to 20% off the price of your car',
        button: 'Get an offer',
        consent: 'By clicking “Send”, you agree to the processing of your personal data.',
      },
      archive: {
        title: 'Archived models',
        modelName: 'Toyota Prius',
        benefit: 'Save up to ₽300,000',
        details: 'More details',
        book: 'Reserve',
      },
      gos: {
        title: 'Family car — government support program',
        rate: 'Rating 4.8',
        rateDescription: '450 reviews',
        discount: '10% discount and low credit 5.9%',
        description: 'Interest-free installment for 12 months up to ₽500,000',
        button: 'Submit application',
        consent: 'By clicking the button, you agree to the processing of your personal data.',
        familyAlt: 'Family with a child',
      },
      trust: {
        title: 'Trusted by our customers',
        siteName: 'Review site',
        dealerName: 'Car dealership name',
        recommend: '90% recommend',
        maps: 'Maps',
        previous: 'Previous ratings',
        next: 'Next ratings',
      },
      footer: {
        catalog: 'Car catalog',
        used: 'Used cars',
        credit: 'Credit and installment',
        offers: 'Special offers',
        taxi: 'Taxi in credit',
        more: 'More',
        sitemap: 'Sitemap',
        catalogTitle: 'CAR',
        catalogTitle2: 'CATALOG',
        creditTitle: 'Credit and installment',
        express: 'Express credit',
        family: 'Family car',
        firstCar: 'First car',
        medical: 'For medical workers',
        installment: 'Installment plan',
        servicesTitle: 'Service center',
        warranty: 'Warranty',
        service: 'Service',
        contactsTitle: 'Contacts',
        hours: 'Daily from 08:00 to 21:00',
        address: 'Russia, Moscow, 38KM MKAD, 6bс1',
        route: 'Route map',
        city: 'Moscow',
        copyright: '© 2021 Auto showroom "ABC AUTO". Official dealer',
        privacy: 'Privacy policy',
        agreement: 'User agreement',
        disclaimer: 'Please note that this website is for informational purposes only and under no circumstances constitutes a public offer as defined by Article 437 of the Civil Code of the Russian Federation.',
        ratingAlt: 'Organization rating in Yandex',
      },
      services: {
        breadcrumbsHome: 'Home',
        breadcrumbsCurrent: 'Service center',
        title: 'Service center',
        intro: 'Our service center specialists have extensive experience servicing vehicles from different manufacturers, both new and used, so they can detect and fix any fault quickly. All work is performed in accordance with the manufacturers\' recommendations.',
        bodyRepair: 'Body repair',
        bodyRepairText: 'Modern equipment allows us to perform body repair of any complexity. We only work with high-quality materials from trusted suppliers.',
        repair: 'Mechanical repair',
        repairText: 'We perform both current and major mechanical repairs, including powertrain maintenance.',
        tire: 'Wheel service',
        tireText: 'Timely tyre replacement is necessary for safe driving. We consider mileage, tyre condition and the season.',
        diagnostics: 'Diagnostics',
        diagnosticsText: 'Quality diagnostics helps identify not only current issues but also prevent possible ones, so the procedure is carried out on a scheduled basis.',
        oilChange: 'Oil change',
        oilChangeText: 'This is a necessary procedure that significantly increases engine life and helps minimize the negative effects of low-quality fuel.',
        maintenance: 'Maintenance',
        maintenanceText: 'This ensures uninterrupted operation of the main vehicle units and assemblies.',
        wheelAlignment: 'Wheel alignment',
        wheelAlignmentText: 'The procedure ensures vehicle stability on the road. It is performed on a schedule or due to handling issues.',
        parts: 'Parts selection',
        partsText: 'The reliability of the car directly depends on the quality of its parts. The service helps choose a quality component suitable for a specific vehicle.',
        insurance: 'Insurance policy extension',
        insuranceText: 'We will select a reliable company offering insurance at fair prices. This helps avoid fraudulent schemes.',
      },
      contacts: {
        breadcrumbsHome: 'Home',
        breadcrumbsCurrent: 'Contacts',
        title: 'Contacts',
        phone: 'Phone',
        address: 'Address',
        addressValue: 'Russia, Moscow, 38KM MKAD, 6Bс1',
        route: 'How to get there',
        routeMkadIn: 'from MKAD (inner side)',
        routeMkadOut: 'from MKAD (outer side)',
        routeCity: 'from the region, from the center',
        company: 'About us',
        companyText: 'We have a huge trading area of more than 5000 square meters, and we have at least 200 cars in stock, both domestic and imported. The ALTERA showroom employs true professionals who know the specifics of each vehicle.',
        slideLabel: 'Slide',
        mapAlt: 'Map of cities presence',
        city: 'Moscow',
      },
      company: {
        breadcrumbsHome: 'Home',
        breadcrumbsCurrent: 'About us',
        title: 'About us',
        intro: 'The official Azimut Varshavka dealer offers a wide range of cars in different colours and trims on the most favorable terms. The showroom has more than two hundred new and used cars. The assortment includes the most popular models from European, Asian and Russian manufacturers. Each client is given a full personal consultation on any car presented. You can learn more about the models in the showroom on the website and from our managers.',
        benefitTitle: 'When you choose the Azimut Varshavka showroom, you get:',
        benefits: [
          'the best car prices in Moscow;',
          'a choice of vehicles from more than two hundred models in different colours and trims;',
          'the opportunity to buy used cars that have passed pre-sale preparation and legal checks;',
          'fast and high-quality document processing;',
          'high service level and an individual approach;',
          'beneficial purchase through Trade-in and recycling programs;',
          'cooperation with the largest banks in Moscow offering the most favorable lending terms;',
          'the opportunity to participate in preferential lending programs such as “Family Car” and “First Car”, as well as favorable terms for medical workers and those who use the Trade-in program as part of the initial payment;',
          'promotions and gifts from the showroom when buying a car.'
        ],
        shouldKnow: 'All questions about availability, colours and vehicle configurations, as well as the operation of the showroom, can always be answered by phone listed on the website or through the feedback form.',
        gratitude: 'We value every client and guarantee a high level of service!',
        slogan: 'Azimut Varshavka — with us, all directions will be conquered!',
        photoTitle: 'Showroom photo',
        citiesTitle: 'Cities of presence',
        workers: 'workers',
        experience: 'on the market',
        partnerBanks: 'Partner banks',
        cityGroups: {
          col1: [
            { id: 1, name: 'Moscow' },
            { id: 2, name: 'Saint Petersburg' },
            { id: 3, name: 'Nizhny Novgorod' },
            { id: 4, name: 'Krasnodar' }
          ],
          col2: [
            { id: 5, name: 'Astrakhan' },
            { id: 6, name: 'Vologda' },
            { id: 7, name: 'Tula' },
            { id: 8, name: 'Arkhangelsk' }
          ]
        }
      },
      brandInfo: {
        notFound: 'Brand not found',
        backHome: 'Back to home',
        filteredTitle: 'Cars by the selected price',
        found: 'Models found',
        empty: 'No cars found in this range.',
        breadcrumbsHome: 'Home',
        breadcrumbsCatalog: 'Car catalog',
        saleTitle: 'Grand sale',
        saleText: 'Get a special price and a gift of choice when buying a car',
        discountLabel: 'Discounts up to',
        guarantee: 'Warranty',
        bestPrice: 'best price',
        credit: 'Affordable',
        creditText: 'credit',
        tradeInTitle: 'Your car trade-in',
        tradeInText: 'in trade-in',
        giftTitle: 'Gift of choice',
        giftText: 'with car purchase',
        favourite: 'Favorites and compare',
        favoriteCompare: 'Favorites and compare',
        inStock: 'In stock',
        deal: 'Trade-in purchase',
        creditOffer: 'Credit',
        sale: 'Sale',
        insurance: 'Insurance',
        insuranceGift: 'as a gift',
        casco: 'CASCO',
        tireKit: 'Tire set',
        benefitUpTo: 'Savings up to',
        from: 'from',
        colorNames: {
          white: 'White',
          pearlWhite: 'Pearl white',
          black: 'Black',
          blackMetallic: 'Black metallic',
          grey: 'Gray',
          greyMetallic: 'Gray metallic',
          silver: 'Silver',
          brown: 'Brown',
          red: 'Red',
          brightRed: 'Bright red',
          blue: 'Blue',
          green: 'Green',
          orange: 'Orange',
          yellow: 'Yellow'
        },
        chooseColor: 'Choose color',
        compare: 'Compare',
        details: 'More details',
        buyWithDiscount: 'Buy with discount',
        calculateCredit: 'Calculate credit',
        moreModel: 'More about the model',
        carAlt: 'Car',
        specialPriceTitle: 'Get a special price',
        specialPriceOnly: 'Only until 10.10.21',
        yourName: 'Your name',
        yourPhone: 'Your phone',
        getOffer: 'Get offer',
        consent: 'By clicking the button, you agree to the processing of your personal data.',
        thanks: 'Thank you! Your application has been accepted.',
        modelRangeTitle: 'Model range and prices of cars',
        emptyRange: 'This brand has no models in the selected price range.',
      },
      error: {
        navCatalog: 'Car catalog',
        navTradeIn: 'Trade-in',
        navCredit: 'Express credit',
        navContacts: 'Contacts',
        title: 'Page not found!',
        message: 'We have launched a new website, making it more convenient and informative. The page you requested may have been moved or removed. You can call us and get qualified assistance from our specialists.',
        home: 'Home',
      }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'ru',
    supportedLngs: ['ru', 'en'],
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag'],
      caches: ['localStorage']
    },
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;